# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_max: .word 0  # Address: 0x1008


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 10, None, 0x1000)
    li $t0, 2
    sw $t0, var_a

    # Quadruple 1: (=, 5, None, 0x1004)
    li $t0, 5
    sw $t0, var_b

    # Quadruple 2: (=, 0, None, 0x1008)
    li $t0, 0
    sw $t0, var_max

    # Quadruple 3: (@, 0x1000, None, t0)  # Load global 'a'
    lw $t0, var_a

    # Quadruple 4: (@, 0x1004, None, t1)  # Load global 'b'
    lw $t1, var_b

    # Quadruple 5: (>, t0, t1, t2)
    slt $t2, $t1, $t0

    # Quadruple 6: (if, t2, None, L0)
    bne $t2, $zero, L0

    # Quadruple 7: (goto, None, None, L1)
    j L1

    # Quadruple 8: (label, None, None, L0)
    L0:

    # Quadruple 9: (@, 0x1000, None, t3)  # Load global 'a'
    lw $t3, var_a

    # Quadruple 10: (=, t3, None, 0x1008)
    sw $t3, var_max

    # Quadruple 11: (goto, None, None, L2)
    j L2

    # Quadruple 12: (label, None, None, L1)
    L1:

    # Quadruple 13: (@, 0x1004, None, t4)  # Load global 'b'
    lw $t4, var_b

    # Quadruple 14: (=, t4, None, 0x1008)
    sw $t4, var_max

    # Quadruple 15: (label, None, None, L2)
    L2:

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
