# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_lt: .word 0  # Address: 0x1008
var_gt: .word 0  # Address: 0x100c
var_eq: .word 0  # Address: 0x1010
var_neq: .word 0  # Address: 0x1014
var_lte: .word 0  # Address: 0x1018
var_gte: .word 0  # Address: 0x101c


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 10, None, 0x1000)
    li $t0, 10
    sw $t0, var_a

    # Quadruple 1: (=, 5, None, 0x1004)
    li $t0, 5
    sw $t0, var_b

    # Quadruple 2: (@, 0x1000, None, t0)  # Load global 'a'
    lw $t0, var_a

    # Quadruple 3: (@, 0x1004, None, t1)  # Load global 'b'
    lw $t1, var_b

    # Quadruple 4: (<, t0, t1, t2)
    slt $t2, $t0, $t1

    # Quadruple 5: (=, t2, None, 0x1008)
    sw $t2, var_lt

    # Quadruple 6: (@, 0x1000, None, t2)  # Load global 'a'
    lw $t2, var_a

    # Quadruple 7: (@, 0x1004, None, t3)  # Load global 'b'
    lw $t3, var_b

    # Quadruple 8: (>, t2, t3, t4)
    slt $t4, $t3, $t2

    # Quadruple 9: (=, t4, None, 0x100C)
    sw $t4, var_gt

    # Quadruple 10: (@, 0x1000, None, t4)  # Load global 'a'
    lw $t4, var_a

    # Quadruple 11: (@, 0x1004, None, t5)  # Load global 'b'
    lw $t5, var_b

    # Quadruple 12: (==, t4, t5, t6)
    xor $t6, $t4, $t5
    sltiu $t6, $t6, 1

    # Quadruple 13: (=, t6, None, 0x1010)
    sw $t6, var_eq

    # Quadruple 14: (@, 0x1000, None, t6)  # Load global 'a'
    lw $t6, var_a

    # Quadruple 15: (@, 0x1004, None, t7)  # Load global 'b'
    lw $t7, var_b

    # Quadruple 16: (!=, t6, t7, t8)
    xor $t8, $t6, $t7
    sltu $t8, $zero, $t8

    # Quadruple 17: (=, t8, None, 0x1014)
    sw $t8, var_neq

    # Quadruple 18: (@, 0x1000, None, t8)  # Load global 'a'
    lw $t8, var_a

    # Quadruple 19: (@, 0x1004, None, t9)  # Load global 'b'
    lw $t9, var_b

    # Quadruple 20: (<=, t8, t9, t10)
    slt $t0, $t9, $t8
    xori $s0, $t0, 1

    # Quadruple 21: (=, t10, None, 0x1018)
    sw $s0, var_lte

    # Quadruple 22: (@, 0x1000, None, t10)  # Load global 'a'
    lw $s0, var_a

    # Quadruple 23: (@, 0x1004, None, t11)  # Load global 'b'
    lw $s1, var_b

    # Quadruple 24: (>=, t10, t11, t12)
    slt $t0, $s0, $s1
    xori $s2, $t0, 1

    # Quadruple 25: (=, t12, None, 0x101C)
    sw $s2, var_gte

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
