# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_result: .word 0  # Address: 0x1008
var_sum: .word 0  # Address: 0x100c
var_diff: .word 0  # Address: 0x1010
var_prod: .word 0  # Address: 0x1014
var_quot: .word 0  # Address: 0x1018
var_mod: .word 0  # Address: 0x101c
var_neg: .word 0  # Address: 0x1020
var_is_greater: .word 0  # Address: 0x1024
var_is_equal: .word 0  # Address: 0x1028
var_is_less_eq: .word 0  # Address: 0x102c
var_complex: .word 0  # Address: 0x1030


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 15, None, 0x1000)
    li $t0, 15
    sw $t0, var_a

    # Quadruple 1: (=, 4, None, 0x1004)
    li $t0, 4
    sw $t0, var_b

    # Quadruple 2: (=, 0, None, 0x1008)
    li $t0, 0
    sw $t0, var_result

    # Quadruple 3: (+, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    add $t2, $t0, $t1

    # Quadruple 4: (=, t0, None, 0x100C)
    sw $t2, var_sum

    # Quadruple 5: (-, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    sub $t2, $t0, $t1

    # Quadruple 6: (=, t0, None, 0x1010)
    sw $t2, var_diff

    # Quadruple 7: (*, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    mul $t2, $t0, $t1

    # Quadruple 8: (=, t0, None, 0x1014)
    sw $t2, var_prod

    # Quadruple 9: (/, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    div $t0, $t1
    mflo $t2  # quotient

    # Quadruple 10: (=, t0, None, 0x1018)
    sw $t2, var_quot

    # Quadruple 11: (%, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    div $t0, $t1
    mfhi $t2  # Get remainder (modulo)

    # Quadruple 12: (=, t0, None, 0x101C)
    sw $t2, var_mod

    # Quadruple 13: (NEG, 0x1004, None, t0)
    lw $t1, var_b
    sub $t2, $zero, $t1

    # Quadruple 14: (=, t0, None, 0x1020)
    sw $t2, var_neg

    # Quadruple 15: (>, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t2, $t1, $t0

    # Quadruple 16: (=, t0, None, 0x1024)
    sw $t2, var_is_greater

    # Quadruple 17: (==, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    xor $t2, $t0, $t1
    sltiu $t2, $t2, 1

    # Quadruple 18: (=, t0, None, 0x1028)
    sw $t2, var_is_equal

    # Quadruple 19: (<=, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t0, $t1, $t0
    xori $t2, $t0, 1

    # Quadruple 20: (=, t0, None, 0x102C)
    sw $t2, var_is_less_eq

    # Quadruple 21: (>, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t2, $t1, $t0

    # Quadruple 22: (if, t0, None, L0)
    bne $t2, $zero, L0

    # Quadruple 23: (goto, None, None, L1)
    j L1

    # Quadruple 24: (label, None, None, L0)
    L0:

    # Quadruple 25: (=, 0x1000, None, 0x1008)
    lw $t0, var_a
    sw $t0, var_result

    # Quadruple 26: (goto, None, None, L2)
    j L2

    # Quadruple 27: (label, None, None, L1)
    L1:

    # Quadruple 28: (=, 0x1004, None, 0x1008)
    lw $t0, var_b
    sw $t0, var_result

    # Quadruple 29: (label, None, None, L2)
    L2:

    # Quadruple 30: (+, 0x1000, 0x1004, t1)
    lw $t0, var_a
    lw $t1, var_b
    add $t3, $t0, $t1

    # Quadruple 31: (*, t1, 2, t2)
    li $t0, 2
    mul $t4, $t3, $t0

    # Quadruple 32: (-, t2, 0x101C, t3)
    lw $t5, var_mod
    sub $t6, $t4, $t5

    # Quadruple 33: (=, t3, None, 0x1030)
    sw $t6, var_complex

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
