# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_max: .word 0  # Address: 0x1008


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 10, None, 0x1000)
    li $t0, 10
    sw $t0, var_a

    # Quadruple 1: (=, 5, None, 0x1004)
    li $t0, 5
    sw $t0, var_b

    # Quadruple 2: (=, 0, None, 0x1008)
    li $t0, 0
    sw $t0, var_max

    # Quadruple 3: (>, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t2, $t1, $t0

    # Quadruple 4: (if, t0, None, L0)
    bne $t2, $zero, L0

    # Quadruple 5: (goto, None, None, L1)
    j L1

    # Quadruple 6: (label, None, None, L0)
    L0:

    # Quadruple 7: (=, 0x1000, None, 0x1008)
    lw $t0, var_a
    sw $t0, var_max

    # Quadruple 8: (goto, None, None, L2)
    j L2

    # Quadruple 9: (label, None, None, L1)
    L1:

    # Quadruple 10: (=, 0x1004, None, 0x1008)
    lw $t0, var_b
    sw $t0, var_max

    # Quadruple 11: (label, None, None, L2)
    L2:

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
