# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_c: .word 0  # Address: 0x1008
var_neg_a: .word 0  # Address: 0x100c
var_mod_result: .word 0  # Address: 0x1010
var_x: .word 0  # Address: 0x1014
var_not_x: .word 0  # Address: 0x1018


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 10, None, 0x1000)
    li $t0, 10
    sw $t0, var_a

    # Quadruple 1: (=, 3, None, 0x1004)
    li $t0, 3
    sw $t0, var_b

    # Quadruple 2: (=, 0, None, 0x1008)
    li $t0, 0
    sw $t0, var_c

    # Quadruple 3: (@, 0x1000, None, t0)  # Load global 'a'
    lw $t0, var_a

    # Quadruple 4: (NEG, t0, None, t1)
    sub $t1, $zero, $t0

    # Quadruple 5: (=, t1, None, 0x100C)
    sw $t1, var_neg_a

    # Quadruple 6: (@, 0x1000, None, t1)  # Load global 'a'
    lw $t1, var_a

    # Quadruple 7: (@, 0x1004, None, t2)  # Load global 'b'
    lw $t2, var_b

    # Quadruple 8: (%, t1, t2, t3)
    div $t1, $t2
    mfhi $t3  # Get remainder (modulo)

    # Quadruple 9: (=, t3, None, 0x1010)
    sw $t3, var_mod_result

    # Quadruple 10: (=, true, None, 0x1014)
    li $t0, 1
    sw $t0, var_x

    # Quadruple 11: (@, 0x1014, None, t3)  # Load global 'x'
    lw $t3, var_x

    # Quadruple 12: (!, t3, None, true)
    sltiu $t4, $t3, 1

    # Quadruple 13: (=, true, None, 0x1018)
    li $t0, 1
    sw $t0, var_not_x

    # Quadruple 14: (@, 0x1000, None, true)  # Load global 'a'
    lw $t4, var_a

    # Quadruple 15: (@, 0x100C, None, t4)  # Load global 'neg_a'
    lw $t5, var_neg_a

    # Quadruple 16: (+, true, t4, t5)
    li $t4, true
    add $t6, $t4, $t5

    # Quadruple 17: (=, t5, None, 0x1008)
    sw $t6, var_c

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
