# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_c: .word 0  # Address: 0x1008
var_neg_a: .word 0  # Address: 0x100c
var_mod_result: .word 0  # Address: 0x1010
var_x: .word 0  # Address: 0x1014
var_not_x: .word 0  # Address: 0x1018


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 10, None, 0x1000)
    li $t0, 10
    sw $t0, var_a

    # Quadruple 1: (=, 3, None, 0x1004)
    li $t0, 3
    sw $t0, var_b

    # Quadruple 2: (=, 0, None, 0x1008)
    li $t0, 0
    sw $t0, var_c

    # Quadruple 3: (NEG, 0x1000, None, t0)
    lw $t0, var_a
    sub $t1, $zero, $t0

    # Quadruple 4: (=, t0, None, 0x100C)
    sw $t1, var_neg_a

    # Quadruple 5: (%, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t2, var_b
    div $t0, $t2
    mfhi $t1  # Get remainder (modulo)

    # Quadruple 6: (=, t0, None, 0x1010)
    sw $t1, var_mod_result

    # Quadruple 7: (=, true, None, 0x1014)
    li $t0, 1
    sw $t0, var_x

    # Quadruple 8: (!, 0x1014, None, t0)
    lw $t3, var_x
    sltiu $t1, $t3, 1

    # Quadruple 9: (=, t0, None, 0x1018)
    sw $t1, var_not_x

    # Quadruple 10: (+, 0x1000, 0x100C, t0)
    lw $t0, var_a
    lw $t4, var_neg_a
    add $t1, $t0, $t4

    # Quadruple 11: (=, t0, None, 0x1008)
    sw $t1, var_c

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
