# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_lt: .word 0  # Address: 0x1008
var_gt: .word 0  # Address: 0x100c
var_eq: .word 0  # Address: 0x1010
var_neq: .word 0  # Address: 0x1014
var_lte: .word 0  # Address: 0x1018
var_gte: .word 0  # Address: 0x101c


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 10, None, 0x1000)
    li $t0, 10
    sw $t0, var_a

    # Quadruple 1: (=, 5, None, 0x1004)
    li $t0, 5
    sw $t0, var_b

    # Quadruple 2: (<, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t2, $t0, $t1

    # Quadruple 3: (=, t0, None, 0x1008)
    sw $t2, var_lt

    # Quadruple 4: (>, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t2, $t1, $t0

    # Quadruple 5: (=, t0, None, 0x100C)
    sw $t2, var_gt

    # Quadruple 6: (==, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    xor $t2, $t0, $t1
    sltiu $t2, $t2, 1

    # Quadruple 7: (=, t0, None, 0x1010)
    sw $t2, var_eq

    # Quadruple 8: (!=, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    xor $t2, $t0, $t1
    sltu $t2, $zero, $t2

    # Quadruple 9: (=, t0, None, 0x1014)
    sw $t2, var_neq

    # Quadruple 10: (<=, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t0, $t1, $t0
    xori $t2, $t0, 1

    # Quadruple 11: (=, t0, None, 0x1018)
    sw $t2, var_lte

    # Quadruple 12: (>=, 0x1000, 0x1004, t0)
    lw $t0, var_a
    lw $t1, var_b
    slt $t0, $t0, $t1
    xori $t2, $t0, 1

    # Quadruple 13: (=, t0, None, 0x101C)
    sw $t2, var_gte

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
