# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_and_result: .word 0  # Address: 0x1008
var_or_result: .word 0  # Address: 0x100c
var_not_a: .word 0  # Address: 0x1010
var_not_b: .word 0  # Address: 0x1014
var_combined: .word 0  # Address: 0x1018


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, true, None, 0x1000)
    li $t0, 1
    sw $t0, var_a

    # Quadruple 1: (=, false, None, 0x1004)
    li $t0, 0
    sw $t0, var_b

    # Quadruple 2: (if_false, 0x1000, None, L0)
    lw $t0, var_a
    beq $t0, $zero, L0

    # Quadruple 3: (=, 0x1004, None, t0)
    lw $t0, var_b
    move $t1, $t0

    # Quadruple 4: (goto, None, None, L1)
    j L1

    # Quadruple 5: (label, None, None, L0)
    L0:

    # Quadruple 6: (=, false, None, t0)
    li $t0, 0
    move $t1, $t0

    # Quadruple 7: (label, None, None, L1)
    L1:

    # Quadruple 8: (=, t0, None, 0x1008)
    sw $t1, var_and_result

    # Quadruple 9: (if, 0x1000, None, L2)
    lw $t0, var_a
    bne $t0, $zero, L2

    # Quadruple 10: (=, 0x1004, None, t0)
    lw $t0, var_b
    move $t1, $t0

    # Quadruple 11: (goto, None, None, L3)
    j L3

    # Quadruple 12: (label, None, None, L2)
    L2:

    # Quadruple 13: (=, true, None, t0)
    li $t0, 1
    move $t1, $t0

    # Quadruple 14: (label, None, None, L3)
    L3:

    # Quadruple 15: (=, t0, None, 0x100C)
    sw $t1, var_or_result

    # Quadruple 16: (!, 0x1000, None, t0)
    lw $t0, var_a
    sltiu $t1, $t0, 1

    # Quadruple 17: (=, t0, None, 0x1010)
    sw $t1, var_not_a

    # Quadruple 18: (!, 0x1004, None, t0)
    lw $t2, var_b
    sltiu $t1, $t2, 1

    # Quadruple 19: (=, t0, None, 0x1014)
    sw $t1, var_not_b

    # Quadruple 20: (!, 0x1004, None, t0)
    lw $t2, var_b
    sltiu $t1, $t2, 1

    # Quadruple 21: (if_false, 0x1000, None, L4)
    lw $t0, var_a
    beq $t0, $zero, L4

    # Quadruple 22: (=, t0, None, t1)
    move $t3, $t1

    # Quadruple 23: (goto, None, None, L5)
    j L5

    # Quadruple 24: (label, None, None, L4)
    L4:

    # Quadruple 25: (=, false, None, t1)
    li $t0, 0
    move $t3, $t0

    # Quadruple 26: (label, None, None, L5)
    L5:

    # Quadruple 27: (!, 0x1000, None, t2)
    lw $t0, var_a
    sltiu $t4, $t0, 1

    # Quadruple 28: (if_false, 0x1004, None, L6)
    lw $t2, var_b
    beq $t2, $zero, L6

    # Quadruple 29: (=, t2, None, t3)
    move $t5, $t4

    # Quadruple 30: (goto, None, None, L7)
    j L7

    # Quadruple 31: (label, None, None, L6)
    L6:

    # Quadruple 32: (=, false, None, t3)
    li $t0, 0
    move $t5, $t0

    # Quadruple 33: (label, None, None, L7)
    L7:

    # Quadruple 34: (if, t1, None, L8)
    bne $t3, $zero, L8

    # Quadruple 35: (=, t3, None, t4)
    move $t6, $t5

    # Quadruple 36: (goto, None, None, L9)
    j L9

    # Quadruple 37: (label, None, None, L8)
    L8:

    # Quadruple 38: (=, true, None, t4)
    li $t0, 1
    move $t6, $t0

    # Quadruple 39: (label, None, None, L9)
    L9:

    # Quadruple 40: (=, t4, None, 0x1018)
    sw $t6, var_combined

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
