# Generated by Compiscript Compiler
# MIPS Assembly Code

# Generated by Compiscript Compiler
.data
var_a: .word 0  # Address: 0x1000
var_b: .word 0  # Address: 0x1004
var_c: .word 0  # Address: 0x1008


.text
.globl main

main:
    # Main prologue
    addiu $sp, $sp, -4
    sw $ra, 0($sp)

    # Quadruple 0: (=, 5, None, 0x1000)
    li $t0, 5
    sw $t0, var_a

    # Quadruple 1: (=, 3, None, 0x1004)
    li $t0, 3
    sw $t0, var_b

    # Quadruple 2: (@, 0x1000, None, t0)  # Load global 'a'
    lw $t0, var_a

    # Quadruple 3: (@, 0x1004, None, t1)  # Load global 'b'
    lw $t1, var_b

    # Quadruple 4: (+, t0, t1, t2)
    add $t2, $t0, $t1

    # Quadruple 5: (=, t2, None, 0x1008)
    sw $t2, var_c

    # Quadruple 6: (@, 0x1008, None, t2)  # Load global 'c'
    lw $t2, var_c

    # Quadruple 7: (*, t2, 2, t3)
    li $t0, 2
    mul $t3, $t2, $t0

    # Quadruple 8: (=, t3, None, 0x1008)
    sw $t3, var_c

    # Main epilogue
    lw $ra, 0($sp)
    addiu $sp, $sp, 4
    li $v0, 10  # Exit syscall
    syscall
